### ISSUE TITLE
Users have to set the number of datapoints twice for buffered measurements

### ISSUE THREAD

**Issue by THuckemann** [qutech/QuMADA#16]
Currently, script.initialization() checks if the number of datapoints set in the buffer settings matches the number of data points specified in the gate_parameters.  Thus, the user has to set them twice. Furthermore, it can cause problems when duration and sampling rate are specified instead of the number of points. 
I'd suggest to ignore the num_points set in the gate_parameters and just give a warning if it doesn't match.

I do not like the idea of splitting up the measurement parameters into different settings dictionaries, but cannot think of a better way...

**Comment by newton-per-sqm** [comment]
Could you write something like an "MWE" measurement script for better understanding? It sounds like it should be possible to fully inherit all necessary buffer settings from the gate_parameters dictionary of a buffered measurement.

**Comment by THuckemann** [comment]
> Could you write something like an "MWE" measurement script for better understanding? It sounds like it should be possible to fully inherit all necessary buffer settings from the gate_parameters dictionary of a buffered measurement.

I am working on an example and the documentation. The problem is that for unbuffered measurements the number of points is always set in the gate_parameters. For buffered measurements, however, it is possible to define e.g. buffer_duration and sampling rate instead of the number of datapoints. This has to be done in the buffer_settings. Moving the buffer setting to into the gate_parameters could cause additional problem when people try to set different num_points for parameters that are connected to the same buffer. Moreover, the number of points is set in the swept parameter, not in the buffered one. 

So far, an assertion error was raised when the numbers of datapoints from the buffer_settings and the gate_parameters were different. As this caused trouble when rounding was involved (especially as the gate_parameter num_points have to be and integer in combination with fixed sampling_rate and duration from the buffer settings), I ended up just using the buffer settings' number of points and providing a warning, when a number of datapoints was also given in the gate_parameters.
I still have the feeling that this might be confusing to people.

**Comment by THuckemann** [comment]
Now only the buffer setting is relevant, but the user gets a warning if it differs from the one set in the gate_parameters.
